### ISSUE TITLE
1.16.4 support

### ISSUE THREAD

**Issue by Volgeop** [LOOHP/InteractionVisualizerLanguages#9]
Please, could you update? LightAPI is already out.
```
[01:22:48] [Craft Scheduler Thread - 26/WARN]: [InteractionVisualizer] Plugin InteractionVisualizer v1.13.9 generated an exception while executing task 28536
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_16_R3.EnumItemSlot exists in class PacketPlayOutEntityEquipment.
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
	at com.loohp.interactionvisualizer.Protocol.ServerPacketSender.spawnArmorStand(ServerPacketSender.java:119) ~[?:?]
	at com.loohp.interactionvisualizer.Managers.PacketManager.lambda$sendArmorStandSpawn$11(PacketManager.java:275) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-259]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-259]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by Volgeop** [comment]
Oh wrong github.
